# Generated by Django 2.1.5 on 2019-02-02 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatroom_admin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='admin_id',
        ),
    ]
