# Generated by Django 2.1.5 on 2019-02-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20190202_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='created_date',
            field=models.DateTimeField(default=1, verbose_name='created_date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(default=1, verbose_name='created_date'),
            preserve_default=False,
        ),
    ]
