# Generated by Django 2.1.5 on 2019-02-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20190202_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='created_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='created_date',
            new_name='date',
        ),
    ]
