# Generated by Django 2.1.5 on 2019-02-02 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20190202_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='chatroom',
            old_name='title',
            new_name='title_text',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nickname',
            new_name='nickname_text',
        ),
    ]
