# Generated by Django 2.1.5 on 2019-02-04 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20190202_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='chatroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.Chatroom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_owner',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
