# Generated by Django 2.1.5 on 2019-02-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20190204_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterFormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.CharField(max_length=80)),
                ('talk_area', models.CharField(max_length=10000)),
            ],
        ),
    ]
