# Generated by Django 2.1.5 on 2019-02-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_enterformmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterformmodel',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
