# Generated by Django 2.1.5 on 2019-02-05 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_enterformmodel_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnterFormModel',
        ),
    ]
