# Generated by Django 2.1.5 on 2019-02-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_delete_enterformmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_on',
            field=models.BooleanField(default=False),
        ),
    ]
